src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 */
/**
 * @ORM\Entity
 * @UniqueEntity("email",
 * message="email.already.used")

 * @UniqueEntity("username",
 * message="username.already.used")
 */

class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $username;

    /**
     * @var string The email
     * @ORM\Column(type="string", unique=true)
     */
    private $email;

    /**
     * @var string the agent the user wants to play
     * @ORM\Column(type="string")
     */
    private $agent;


    /**
     *
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $avatar;

    /**
     * @ORM\Column(type="string", length=150)
     */
    private $level;

    /**
     * @ORM\Column(type="datetime")
     */
    private $DateSignIn;

    /**
     * @ORM\Column(type="string", length=200)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=150, nullable=true)
     */
    private $languages;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $friendask;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $friendsend;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $teams;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $online;

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    /**
     * @Assert\Regex(
     *          pattern = "(^.*[^\(.*[!@#$%^&*\]]{4,12}$)",
     *          match=true,
     *          message="username.not.valid")
     */
    public function getUsername(): string
    {
        return (string) $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }



     /**
     * Email.
     *
     * @see UserInterface
     */
    /**
     * @Assert\Regex(
     *          pattern = "(^([a-zA-Z0-9_\-\.]+)@([a-zA-Z0-9_\-\.]+)\.([a-zA-Z]{2,5})$)",
     *          match=true,
     *          message="email.not.valid")
     */
    public function getEmail(): string
    {
        return (string) $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * Agent.
     *
     * @see UserInterface
     */

    public function getAgent(): string
    {
        return (string) $this->agent;
    }

    public function setAgent(string $agent): self
    {
        $this->agent = $agent;

        return $this;
    }

     /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    /**
     * @Assert\Regex(
     *          pattern = "(^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]{8,}$)",
     *          match=true,
     *          message="password.not.valid")
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    
    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

     /**
     * Many Users have Many Users.
     * @ORM\ManyToMany(targetEntity="User", mappedBy="myFriends")
     */
    private $friendsWithMe;

    /**
     * Many Users have many Users.
     * @ORM\ManyToMany(targetEntity="User", inversedBy="friendsWithMe")
     * @ORM\JoinTable(name="friends",
     *      joinColumns={@ORM\JoinColumn(name="user_id", referencedColumnName="id")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="friend_user_id", referencedColumnName="id")}
     *      )
     */
    private $myFriends;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $announce_status = "0";

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $premium ='0';


    public function __construct() {
        $this->friendsWithMe = new \Doctrine\Common\Collections\ArrayCollection();
        $this->myFriends = new \Doctrine\Common\Collections\ArrayCollection();
    }

    public function getAvatar(): ?string
    {
        return $this->avatar;
    }

    public function setAvatar(?string $avatar): self
    {
        $this->avatar = $avatar;

        return $this;
    }

    public function getLevel(): ?string
    {
        return $this->level;
    }

    public function setLevel(string $level): self
    {
        $this->level = $level;

        return $this;
    }

    public function getDateSignIn(): ?\DateTimeInterface
    {
        return $this->DateSignIn;
    }

    public function setDateSignIn(\DateTimeInterface $DateSignIn): self
    {
        $this->DateSignIn = $DateSignIn;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getLanguages(): ?string
    {
        return $this->languages;
    }

    public function setLanguages(?string $languages): self
    {
        $this->languages = $languages;

        return $this;
    }

    public function getFriendask(): ?string
    {
        return $this->friendask;
    }

    public function setFriendask(?string $friendask): self
    {
        $this->friendask = $friendask;

        return $this;
    }

    public function getFriendsend(): ?string
    {
        return $this->friendsend;
    }

    public function setFriendsend(?string $friendsend): self
    {
        $this->friendsend = $friendsend;

        return $this;
    }

    public function getTeams(): ?string
    {
        return $this->teams;
    }

    public function setTeams(?string $teams): self
    {
        $this->teams = $teams;

        return $this;
    }

    public function getOnline(): ?string
    {
        return $this->online;
    }

    public function setOnline(?string $online): self
    {
        $this->online = $online;

        return $this;
    }

    public function getMyFriends(){
        return $this->myFriends;
    }

    public function getfriendsWithMe(){
        return $this->friendsWithMe;
    }

    public function addFriend(User $friend){
        $this->myFriends->add($friend);
        // $friend->myFriends->add($this);
    }

    public function removeFriend(User $friend){
        $this->myFriends->removeElement($friend);
    }

    public function getAnnounceStatus(): ?string
    {
        return $this->announce_status;
    }

    public function setAnnounceStatus(string $announce_status): self
    {
        $this->announce_status = $announce_status;

        return $this;
    }

    public function getPremium(): ?string
    {
        return $this->premium;
    }

    public function setPremium(string $premium): self
    {
        $this->premium = $premium;

        return $this;
    }



}

templates/profil/profil_account.html.twig
{% extends 'baseprofile.html.twig' %}

{% block contentinnercontainer %}
<div id="particles-js"></div>
<div class="container_account_section">

    <p class="titlesection">{% trans %}myaccount{% endtrans %}</p>

    <div class="contentprofilesection">
        <p><b>{% trans %}mail{% endtrans %} : </b>{{ app.user.email }}</p>
        <p><b>{% trans %}username{% endtrans %} : </b>{{ app.user.username }}</p>
        <p><b>{% trans %}datelogin{% endtrans %} : </b>{{ app.user.datesignin |date('d/m/Y') }}</p>
        <p><b>{% trans %}role{% endtrans %} : </b>{{ app.user.roles.0[5:] | trans}}</p>
        <div class="premiumaccountpofile">

        </div>
    </div>
</div>

    
{% endblock %}
{% block script %}
<script src="/js/particlesconfig.js"></script>
{% endblock %}

templates/profil/profil_addfriend.html.twig
{% extends 'baseprofile.html.twig' %}

{% block contentinnercontainer %}
<div id="particles-js"></div>
<div class="friendpage" data-page='{{selectedpage}}'>
    {% if friendadded == "newfriend" %}

        {{friendnameadded}} and you are now friends

    {% else %}    
        {{friendnameadded}} and you are already friends
    {% endif %}

    <p>You will be redirected in <span class="redirectedin">5</span> seconds</p>
    
</div>
    
{% endblock %}

{% block script %}


<script>
    setTimeout(
        
        function(){
            
            if ($('.friendpage').attr('data-page') == "addfriend"){
                location.href = document.referrer;
            }
            else if ($('.friendpage').attr('data-page') == "msgfriend"){
                location.href = "../friends/";
            }
            else if ($('.friendpage').attr('data-page') == "addfriendtoteam"){
                location.href = "../teams/";
            }
            
        }
        ,5000
    )
    
    var i = 4;          
    setInterval(
        function(){
            $('.redirectedin').html(i);
            i--;
        },1000
        
    );

  
</script>

<script src="/js/particlesconfig.js"></script>

{% endblock %}

templates/profil/profil_announces.html.twig
{% extends 'baseprofile.html.twig' %}

{% block contentinnercontainer %}
<div id="particles-js"></div>
<div class="container_solo_announces_summary">

    <p class="titlesection">{% trans %}announces{% endtrans %}</p>

    {% if announces[0] is defined %}

    {% for announce in announces %}

    <div class="solo_announces_summary">
         <div class="solo_announces_summary_units solo_announces_summary_title">{{ announce.title }}</div>
         <div class="solo_announces_summary_units solo_announces_summary_date">{{ announce.date |date('d/m/Y')}}</div>
         <div class="solo_announces_summary_units solo_announces_summary_username">{{ announce.username }}</div>
         <div class="solo_announces_summary_units solo_announces_summary_agentplayed">{{ announce.agentplayed }}</div>
         <div class="solo_announces_summary_units solo_announces_summary_description">{{ announce.description }}</div>
         <div class="solo_announces_summary_units solo_announces_summary_level">{{ announce.level }}</div>
         <div class="solo_announces_summary_units solo_announces_summary_languages">
             {% if announce.french == '1' %} <span>French </span> {% endif %}{% if announce.english == '1' %} <span>English </span> {% endif %}{% if announce.spanish == '1' %} <span>Spanish </span> {% endif %}
        </div>
         <div class="solo_announces_summary_units solo_announces_summary_delete"><button onclick="confirmation();" class="button_general_myannounces">Supprimer</button><p id="demo"></p></div>
         <div class="space_announces_solo_top"></div>
    </div>

    {% endfor %}

    {% else %}

    <span>You don't have any announce yet.</span>
    <a class="post_an_announce_now_solo" href="../createannounces/">Post an announce now !</a>
    
{% endif %}
{#{{ announces.0.username }}#}
    
</div>

<script>

    function confirmation(){

        Swal.fire({
            title: 'Are you sure?',
            text: "",
            icon: 'warning',
            background: '#111221',
            border: '#ff4654 solid 2px',
            showCancelButton: true,
            confirmButtonColor: '#190530',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Yes, delete it!'
        }).then((result) => {
            if (result.value) {
                Swal.fire(
                    'Deleted!',
                    'Your file has been deleted.',
                    'success'
                );
                window.location.href='../deleteannounce';
            }
        })

    }

    </script>

    <script src="/js/particlesconfig.js"></script>
{% endblock %}

templates/profil/profil_createannounces.html.twig
{% extends 'baseprofile.html.twig' %}

{% block contentinnercontainer %}
<div id="particles-js"></div>
<div class="container_announces_section">

    {% if app.user.agent == "none_configured" %}
    
        <div class="space_postmyprofile"><a href="../profil/" class="postmyprofile">{% trans %} agentbefore {% endtrans %}</a></div>

    {% else %}

        <p class="titlesection">Post my profile to be recruited</p>

        {{ form_start(formAnnounces) }}

        <div class="titleannounce_solo">
            <span class="label_announce_solo">Announce Title :</span>
            {{ form_row(formAnnounces.title,{'label':false}, { 'attr': {'placeholder': 'The title I want' } }) }}
        </div>

        {{ form_row(formAnnounces.username , { 'attr': {'value': app.user.username } }) }}
        {{ form_row(formAnnounces.avatar , { 'attr': {'value': app.user.avatar } }) }}

        <div class="favoriteagent_announce_solo">
            <span>Favorite Agent : {{ app.user.agent }} </span>
                </br> 
            <img class="agentimg agentimgannounce" src="{{asset('images/Avatars/Agents/PNG/' ~ app.user.agent ~ '120x120.png')}}">
        </div>

        {{ form_row(formAnnounces.agentplayed , { 'attr': {'value': app.user.agent } }) }}

        <div class="descriptionblock_announce_solo">
            <span>Description : </span>
                </br> 
        <span class="description_announce_solo">{{ app.user.description }}</span>
        </div>

        {{ form_row(formAnnounces.description , { 'attr': {'value': app.user.description } }) }}
        

        {{ form_row(formAnnounces.level , { 'attr': {'value': app.user.level } }) }}
        {{ form_row(formAnnounces.status , { 'attr': {'value': '1' } }) }}

            <p>Languages Spoken :</p>

            <div class="languagesspoken_solo">
                {{ form_row(formAnnounces.french) }}
                {{ form_row(formAnnounces.english) }}
                {{ form_row(formAnnounces.spanish) }}
            </div>

        <button type="submit" class="button_general announces_post_button">Post my announce</button>
        {{ form_end(formAnnounces) }}
{% endif %}
</div>

{% endblock %}
{% block script %}

<script src="/js/particlesconfig.js"></script>
{% endblock %}

templates/profil/profil_profil.html.twig
{% extends 'baseprofile.html.twig' %}

{% block contentinnercontainer %}

<div id="particles-js"></div>

{#    <p>LE PROFIL JOUEUR</p>#}

    <div class="container_currentagentimg">

        {% if app.user.agent == "none_configured" %}
        <img class="currentagentimg" src="{{asset('images/Jett/Jett.png')}}"> 
        {% else %}
        <img class="currentagentimg" src="{{asset('images/' ~ app.user.agent ~ '/' ~ app.user.agent ~ '.png')}}">
        {% endif %}

    </div>

    <div class="container_profil_section">

        <p class="titlesection">{% trans %}profil{% endtrans %}</p>

        {{ form_start(formMyProfile,{'attr': {'class': 'form_my_profile'}})  }}

        <div class="visible_profile">
            
            <label class="checkbox_profile">
                <input type="checkbox" class="checkbox_profile_input" data-check="{{app.user.announceStatus }}">
                <span class="checkmark_profile"></span>
            </label>
            <span>Make my profile visible for recruitment</span>
        </div>

        <div class="upload_avatar_profile fontsize1_6">Avatar : {{ form_row(formMyProfile.avatar,{"label" : false})}}</div>

                <div class="mydesc_profil_title fontsize1_6">
                    {% trans %}mydesc{% endtrans %} <img src="{{asset('images/editicon.png')}}" class="editicon edit_desc_button" onclick="editDescription()">
                </div>

                {{ form_row(formMyProfile.Description,{'label':false} ) }}

        <div class="level_agent_languages">
            {{ form_row(formMyProfile.Agent) }}
            <p class="fontsize1_6">{% trans %}mylevel{% endtrans %} : {{ app.user.level }}</p>
        </div>
        
        {% if app.user.agent == "none_configured" %}
        <span class="fontsize1_6">{% trans %}favagent{% endtrans %} : {% trans %}chooseagentbelow{% endtrans %}</span> 
        {% else %}        
        <span class="fontsize1_6">{% trans %}favagent{% endtrans %} : {{ app.user.agent }}</span>
        {% endif %}

        <div class="agents_myprofile">

            {%  for Agent in Agents %}

                {% if Agent is same as(app.user.agent) %}
                <img style="display: none" class="agentimg selectedagent" id="{{ Agent }}"  data-status="selected" onclick="UpdateProfile(this.id,'selected')" src="{{ asset('images/Avatars/Agents/PNG/' ~ Agent ~ '120x120.png') }}" alt="{{ Agent }}">
                {% else %}
                    <img class="agentimg nonselectedagent" id="{{ Agent }}" data-status="nonselected" onclick="UpdateProfile(this.id,'nonselected')" src="{{ asset('images/Avatars/Agents/PNG/' ~ Agent ~ '120x120.png') }}" alt="{{ Agent }}">
                {% endif %}

            {% endfor %}

        </div>
        
        <div class="container_button_profile">
            <button onclick="notifDescriptionsaved()" type="submit" class="button_general button_general_profil">{% trans %}savechanges{% endtrans %}</button>
        </div>
        {{ form_end(formMyProfile) }}

    
    </div>


    
{% endblock %}

{% block script %}
<script>
    $( ".mydesc_profil_title" ).append( "<div class=\"divide\"></div>" );
 
    if($(".checkbox_profile_input").attr('data-check') == "1") {
        $('.visible_profile > span').html('You can be hired. Click to leave the list')
        $(".checkbox_profile_input").prop("checked",true)
    }
    else {
        $('.visible_profile > span').html('Make my profile visible for recruitment')
        $(".checkbox_profile_input").prop("checked",false)
    }

    $('.checkbox_profile_input').change(function(){ 
        if($(this).attr('data-check') == "1") {
            var checked = "0"
              $(this).attr('data-check','0')
              $('.visible_profile > span').html('Make my profile visible for recruitment')
              
        }
        else {
            var checked = "1"
            $(this).attr('data-check','1')
            $('.visible_profile > span').html('You can be hired')
            
        }

        $.ajax({
            url : "/scripts/announcestatus.php",
            type : "POST",
            data : 'id={{app.user.id}}&user={{app.user.username}}&announcestatus='+checked,
            
            success : function(html){

              }
        });
    })
</script>

<script src="{{asset('js/particlesconfig.js')}}"></script>

{% endblock %}

templates/profil/profil_teamsINPROGRESS.html.twig
{% extends 'baseprofile.html.twig' %}

{% block contentinnercontainer %}

<!-- <div id='particles-js'></div> -->

  <div class="teams_menu_block">

    {% set teamleft = 5 - teamsofusernumber %}

    {% for key,team in teamsofuser %}
      
      <div class="teams_menu" data-team='teamexist' data-teamname ='{{team.name}}' data-teamid ='{{team.id}}' data-motto ='{{team.title}}' data-creator ='{{team.creator}}' data-date ='{{team.date | date("H:i:s")}}' data-availableslots ='{{team.availableslots}}' data-logo ='{{team.logo}}' data-mediumlevel ='{{team.mediumlevel}}' data-premiumstatus ='{{team.premiumstatus}}' data-member1 ='{{team.member1}}' data-member2 ='{{team.member2}}' data-member3 ='{{team.member3}}' data-member4 ='{{team.member4}}' >
        <div style="background: url( {{ asset('images/teams_logo/' ~ team.logo ~ '') }});background-size: cover;" class="inner_teams_menu" id="{{key}}" onclick="showmatchingteam()">
          
        </div>
      </div>
    {% endfor %}

    {% if teamleft > 0 %}
          
    {% for key,i in teamsofusernumber..4 %}
    
    <div class="teams_menu" data-team='createnew'>
      <div class="inner_teams_menu" id="{{i}}" onclick="showmatchingteam()">
        
      </div>
    </div>
    {% endfor %}
    
    {% endif %}

  </div>

  <div class="container_teams_section">

  <p class="titlesection">My teams</p>

  <div class="container_team_profil 1" id="container_team_profil">

    <div class="team_block">

      <div class="visible_team_block"></div>

      <div class="team_name">
        <span class="team_name_span">The informations of your team will be here</span>
        <img class="delete_team" src="">
      </div>
      <div class="motto_team">
        Click on your team logo above to display informations or click on the + to add new one.
      </div>

      <div class="description_team_profil"></div>

      <div class="team_logo_display"><img class="team_logo" src=""></div>

      <div class="edit_team"><button>save</button></div>

      <div class="members_block"></div>

    </div>


    <div style="display: none;" class="container_teams_create">
      <span class="create_my_team_txt">Create my Squad</span>
  
      {{ form_start(formTeams, {"attr": {'class':'form_squad'}}) }}

      <div class="create_team_name"><span class="name_team_label">Name : </span>{{ form_row(formTeams.name, {'label':false}) }}</div>
  
      <div class="create_team_motto"><span class="motto_team_label">Motto : </span>{{ form_row(formTeams.title, {'label':false}) }}</div>

      <div class="create_team_logo"><span>Team logo : </span>{{ form_row(formTeams.logo, {'label':false}) }}</div>

      <div class="create_team_premiumstatus">{{ form_row(formTeams.premium_status) }}</div>
  
      
  
      <!-- <div class="create_team_availablesslots"><span>Slots Availables : </span>{{ form_row(formTeams.availableslots, {'label':false}) }}</div>
      {{ form_row(formTeams.member1) }}
      {{ form_row(formTeams.member2) }}
      {{ form_row(formTeams.member3) }}
      {{ form_row(formTeams.member4) }}
  
      <div class="add_members_group">
      {% for i in 1..4 %}
  
      <div class="dropdown dropdown{{ i }}">
          <div onclick="myFunction({{ i }})" data-member = "{{ i }}" class="dropbtn"><img class="img_add_member img_add_member{{ i }}" src="{{ asset('../images/addmember.png') }}"> </br> <span class="name{{ i }}"></span></div>
          <div id="myDropdown{{ i }}" class="dropdown-content">
              <input type="text" placeholder="Search for a member" id="myInput{{ i }}" onkeyup="filterFunction({{ i }})">
  
              {% for key,member in members %}
                  <a id ="{{ key }}" onclick="selectMember(this.id,{{ i }})" data-avatar = "{{ member }}" href="#">{{ key }}</a>
                  
  
              {% endfor %}
          </div>
      </div>
  
      
  
  {% endfor %}
  
      </div> -->
  
      <div class="button_create_team"><button class="button_general button_general_createteam" type="submit">Create a team</button></div>
  
      {{ form_end(formTeams) }}
  
  </div>
  
  </div>

</div>




{% endblock %}

{% block script %}
<script>

  $('.form_squad').hover(function(){
    
    if (typeof($("#form_logo")[0].files[0]) == 'undefined'){
      $('.button_general_createteam').attr("disabled", true);
    }
    else if (($("#form_logo")[0].files[0].size > 1024000)){
      $('.button_general_createteam').attr("disabled", true);
      if(!$( ".toobigimage" ).length){
        $('.create_team_logo').after('<span class="toobigimage"> image trop grosse</span>')
      }
      
    }
    else{
      $('.button_general_createteam').attr("disabled", false);
      $('.toobigimage').remove();
    }
})

  function showmatchingteam() {
    var teamid = event.srcElement.id;
    $("#container_team_profil").removeClass();
    $("#container_team_profil").addClass(teamid);
    $("#container_team_profil").addClass('container_team_profil');
    $('.team_name_span').html('Team : '+teamid );

    }

    $('.teams_menu').click(function(){
      $('.teams_menu').removeClass('selected_team');
      $(this).addClass('selected_team');
      console.log($(this).attr('data-team'))
      var members = {{ members|json_encode|raw }};
      if ($(this).attr('data-team') == "createnew"){
        $('.team_block , .team_block_right, .members_block').css('display', 'none');
        $('.container_teams_create').css('display', 'block');
      }
      else {
        $('.container_teams_create').css('display', 'none');
        $('.team_block , .team_block_right, .members_block,.description_team_profil').css('display', 'block');
        $('.visible_team_block').html('<div class="visible_profile"><label class="checkbox_profile"><input type="checkbox" class="checkbox_profile_input" data-check="{{app.user.announceStatus }}"><span class="checkmark_profile"></span></label><span>Make my team visible for recruitment</span></div>');
        $('.members_block').css('display', 'flex');
        $('.team_logo').attr('src','../../../images/teams_logo/'+$(this).attr('data-logo'));
        $('.description_team_profil').html('Juanito la descriptionne');
        $('.motto_team').html($(this).attr('data-motto'));
        $('.team_name_span').html($(this).attr('data-teamname'));
        $('.member_team0, .member_team1, .member_team2, .member_team3, .member_team4 ').remove();
        $('.members_block').append('<div class="member_team member_team0"><img class="member_team_avatar member_team_avatar0" src="'+members[$(this).attr('data-creator')]+'"><span class="member_team_name member_team_name0">'+$(this).attr('data-creator')+'</span></>');
        
        $('.delete_team').attr('src', '../../../images/menu_logos/delete.png')
        var id = $(this).attr('data-teamid');
        $('.delete_team').click(function(){ location.href='../deleteteam/'+id+'' })

        

        for (let i = 1; i <= 4; i++) {
          var member = $(this).attr('data-member'+i);
          if (member !== ''){
            $('.members_block').append('<div class="member_team member_team'+i+'"><img class="member_team_avatar member_team_avatar'+i+'" src="'+members[$(this).attr('data-member'+i)]+'"><span class="member_team_name member_team_name'+i+'">'+$(this).attr('data-member'+i)+'</span></div>');
          }

        }
      }
    })


    function selectMember(id,i) {
    document.getElementById("myDropdown"+i+"").classList.toggle("show");
 
   $('#form_member'+i+'').val(id);
    var avatar = $('#'+id).attr('data-avatar');
    $('.img_add_member'+i).attr('src',avatar);
    $('.name'+i).html(id)
    }

    function myFunction(i) {

        if ($( "#myDropdown"+i+"" ).hasClass( "show" )){
            $( "#myDropdown"+i+"" ).removeClass( "show" )
        }
        else if ($( ".show" ).hasClass( "show" )) {
            $( ".show" ).removeClass( "show" );
            document.getElementById("myDropdown"+i+"").classList.toggle("show");   
        }
        else {
         document.getElementById("myDropdown"+i+"").classList.toggle("show");   
        }
        
        
        
        }
    function filterFunction(i) {
        var input, filter, ul, li, a, i;
        input = document.getElementById("myInput"+i+"");
        filter = input.value.toUpperCase();
        div = document.getElementById("myDropdown"+i+"");
        a = div.getElementsByTagName("a");
        for (i = 0; i < a.length; i++) {
        txtValue = a[i].textContent || a[i].innerText;
        if (txtValue.toUpperCase().indexOf(filter) > -1) {
        a[i].style.display = "";
        }
        else {
        a[i].style.display = "none";
        }
        }
    }

 </script>

 <script src="{{asset('js/particlesconfig.js')}}"></script>
{% endblock %}